apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    app: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.worker.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker
    spec:
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
          imagePullPolicy: Always
          # Nếu worker là background job thì KHÔNG cần port
          # ports:
          #   - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"